# Generated by Django 3.2.12 on 2022-03-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SportsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_desc', models.TextField()),
                ('image_file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SportsHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SportsParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('participant_email', models.EmailField(max_length=254)),
                ('participant_mobile', models.CharField(max_length=12)),
                ('participant_department', models.CharField(max_length=100)),
                ('participant_year', models.CharField(max_length=15)),
                ('participant_score', models.IntegerField(blank=True, null=True)),
                ('participant_event_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_event_1', to='sports.sportsevent')),
                ('participant_event_2', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_event_2', to='sports.sportsevent')),
                ('participant_event_3', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_event_3', to='sports.sportsevent')),
                ('participant_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportshouse')),
            ],
        ),
        migrations.CreateModel(
            name='SportsEventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_dateTime', models.DateTimeField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportsevent')),
                ('rank1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank1', to='sports.sportsparticipant')),
                ('rank2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank2', to='sports.sportsparticipant')),
                ('rank3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank3', to='sports.sportsparticipant')),
            ],
        ),
    ]
