# Generated by Django 4.0.2 on 2022-04-20 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsgallery',
            name='image_desc',
        ),
        migrations.RemoveField(
            model_name='sportsgallery',
            name='image_name',
        ),
        migrations.AddField(
            model_name='sportsgallery',
            name='event_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.sportsevent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsgallery',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
