# Generated by Django 4.0.2 on 2022-02-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_sportsgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsparticipant',
            name='participant_email',
            field=models.EmailField(default='em@em.c', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsparticipant',
            name='participant_mobile',
            field=models.IntegerField(default=79),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsparticipant',
            name='participant_semester',
            field=models.CharField(default='s1', max_length=15),
            preserve_default=False,
        ),
    ]
