# Generated by Django 4.0.2 on 2022-02-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_alter_sportsparticipant_participant_event_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsparticipant',
            name='participant_mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
