# Generated by Django 4.0.2 on 2022-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_alter_sportsparticipant_participant_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsparticipant',
            name='participant_mobile',
            field=models.CharField(max_length=12),
        ),
    ]
