# Generated by Django 4.0.2 on 2022-02-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_alter_sportsparticipant_participant_event_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsparticipant',
            name='participant_event_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participant_event_1', to='sports.sportsevent'),
            preserve_default=False,
        ),
    ]
