# Generated by Django 4.0.2 on 2022-02-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_alter_sportsparticipant_participant_event_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportsparticipant',
            old_name='participant_semester',
            new_name='participant_year',
        ),
    ]
