# Generated by Django 4.0.2 on 2022-02-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_rename_participant_semester_sportsparticipant_participant_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportseventdetail',
            name='event_time',
            field=models.CharField(max_length=10),
        ),
    ]
