# Generated by Django 4.0.2 on 2022-03-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_remove_sportseventdetail_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportsevent')),
                ('rank1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank1', to='sports.sportsparticipant')),
                ('rank2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank2', to='sports.sportsparticipant')),
                ('rank3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank3', to='sports.sportsparticipant')),
            ],
        ),
    ]
