# Generated by Django 4.0.2 on 2022-02-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SportsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SportsParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('participant_department', models.CharField(max_length=100)),
                ('participant_score', models.IntegerField(blank=True, null=True)),
                ('participant_event_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_event_1', to='mainapp.sportsevent')),
                ('participant_event_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_event_2', to='mainapp.sportsevent')),
                ('participant_event_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_event_3', to='mainapp.sportsevent')),
                ('participant_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.house')),
            ],
        ),
        migrations.CreateModel(
            name='SportsEventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sportsevent')),
            ],
        ),
        migrations.CreateModel(
            name='ArtsParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('participant_department', models.CharField(max_length=100)),
                ('participant_score', models.IntegerField(blank=True, null=True)),
                ('participant_event_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_event_1', to='mainapp.artsevent')),
                ('participant_event_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_event_2', to='mainapp.artsevent')),
                ('participant_event_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_event_3', to='mainapp.artsevent')),
                ('participant_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.house')),
            ],
        ),
        migrations.CreateModel(
            name='ArtsEventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.artsevent')),
            ],
        ),
    ]
