# Generated by Django 4.0.2 on 2022-04-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_remove_artseventdetail_event_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=4)),
            ],
        ),
    ]
