# Generated by Django 4.0.2 on 2022-02-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_artsparticipant_participant_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artsparticipant',
            old_name='participant_semester',
            new_name='participant_year',
        ),
    ]
