# Generated by Django 4.0.2 on 2022-02-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_rename_participant_semester_artsparticipant_participant_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artseventdetail',
            name='event_time',
            field=models.CharField(max_length=10),
        ),
    ]
