# Generated by Django 4.0.2 on 2022-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0006_remove_artseventdetail_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsparticipant',
            name='participant_mobile',
            field=models.CharField(max_length=12),
        ),
    ]
