# Generated by Django 4.0.2 on 2022-03-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0007_alter_artsparticipant_participant_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtsWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.artsevent')),
                ('rank1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank1', to='arts.artsparticipant')),
                ('rank2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank2', to='arts.artsparticipant')),
                ('rank3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank3', to='arts.artsparticipant')),
            ],
        ),
    ]
