# Generated by Django 4.0.2 on 2022-03-02 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0008_artswinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='artseventdetail',
            name='rank1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank1', to='arts.artsparticipant'),
        ),
        migrations.AddField(
            model_name='artseventdetail',
            name='rank2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank2', to='arts.artsparticipant'),
        ),
        migrations.AddField(
            model_name='artseventdetail',
            name='rank3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank3', to='arts.artsparticipant'),
        ),
        migrations.DeleteModel(
            name='ArtsWinner',
        ),
    ]
